; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Sat Oct 21 2017 16:11:48 GMT-0400 (US Eastern Daylight Time)

; Wait for set temperatures to be reached
M116 P0
